import XCTest
@testable import WhoopProtocol

/// Cross-language guarantee that Swift extractHistoricalStreams == Python
/// extract_historical_streams over the 60 type-47 HISTORICAL_DATA (V24) records.
/// biometric_streams_golden.json is generated by scripts/gen_golden.py.
final class BiometricStreamsParityTests: XCTestCase {
    // HISTORICAL_DATA uses the record's own unix ts. This is a DECODE-parity test, so we keep the clock
    // non-stale (device == wall → offset 0, well under the FIX #72 stale-clock threshold) so the offset
    // correction is a no-op and type-47 ts == the record's raw unix — exactly what the Python golden
    // encodes. (The stale-clock correction has its own tests in Whoop4HistoricalV24HardwareTests.)
    private let deviceClockRef = 1_736_365_593
    private let wallClockRef = 1_736_365_593

    private struct FrameEntry: Decodable { let hex: String }
    private struct HRGold: Decodable, Equatable { let ts: Int; let bpm: Int }
    private struct RRGold: Decodable, Equatable { let ts: Int; let rr_ms: Int }
    private struct SpO2Gold: Decodable, Equatable { let ts: Int; let red: Int; let ir: Int; let unit: String }
    private struct TempGold: Decodable, Equatable { let ts: Int; let raw: Int; let unit: String }
    private struct RespGold: Decodable, Equatable { let ts: Int; let raw: Int; let unit: String }
    private struct GravGold: Decodable, Equatable {
        let ts: Int; let x: Double; let y: Double; let z: Double; let unit: String
    }
    private struct BioGold: Decodable {
        let hr: [HRGold]; let rr: [RRGold]
        let spo2: [SpO2Gold]; let skin_temp: [TempGold]
        let resp: [RespGold]; let gravity: [GravGold]
    }

    private func resourceURL(_ name: String, _ ext: String) throws -> URL {
        try XCTUnwrap(Bundle.module.url(forResource: name, withExtension: ext),
                      "missing \(name).\(ext) — run scripts/gen_golden.py")
    }
    private func bytes(_ s: String) -> [UInt8] {
        var out = [UInt8](); out.reserveCapacity(s.count / 2); var i = s.startIndex
        while i < s.endIndex { let j = s.index(i, offsetBy: 2)
            out.append(UInt8(s[i..<j], radix: 16)!); i = j }
        return out
    }

    func testSwiftBiometricStreamsMatchPythonGolden() throws {
        let frames = try JSONDecoder().decode(
            [FrameEntry].self, from: Data(contentsOf: resourceURL("frames", "json")))
        let gold = try JSONDecoder().decode(
            BioGold.self, from: Data(contentsOf: resourceURL("biometric_streams_golden", "json")))

        // Parse all frames, keep the type-47 HISTORICAL_DATA records in order.
        let v24 = frames.map { parseFrame(bytes($0.hex)) }
            .filter { $0.ok && $0.typeName == "HISTORICAL_DATA" }
        XCTAssertEqual(v24.count, 60, "expected the 60 V24 records from gen_golden.py")

        let s = extractHistoricalStreams(v24, deviceClockRef: deviceClockRef, wallClockRef: wallClockRef)

        XCTAssertEqual(s.hr, gold.hr.map { HRSample(ts: $0.ts, bpm: $0.bpm) })
        XCTAssertEqual(s.rr, gold.rr.map { RRInterval(ts: $0.ts, rrMs: $0.rr_ms) })
        XCTAssertEqual(s.spo2, gold.spo2.map { SpO2Sample(ts: $0.ts, red: $0.red, ir: $0.ir, unit: $0.unit) })
        XCTAssertEqual(s.skinTemp, gold.skin_temp.map { SkinTempSample(ts: $0.ts, raw: $0.raw, unit: $0.unit) })
        XCTAssertEqual(s.resp, gold.resp.map { RespSample(ts: $0.ts, raw: $0.raw, unit: $0.unit) })
        XCTAssertEqual(s.gravity, gold.gravity.map {
            GravitySample(ts: $0.ts, x: $0.x, y: $0.y, z: $0.z, unit: $0.unit) })

        // Sanity: the fixture must actually exercise every biometric stream.
        XCTAssertGreaterThan(s.hr.count, 0)
        XCTAssertGreaterThan(s.spo2.count, 0)
        XCTAssertGreaterThan(s.gravity.count, 0)
    }
}
