import SwiftUI
import Foundation
import os

// MARK: - Phosphor icons
//
// The NOOP v2 design references icons by their Iconify `ph` names (`heart-light`, `play-fill`, ...).
// The Light and Fill weights of Phosphor Icons (MIT, see Resources/phosphor-LICENSE.txt) ship as
// `Resources/phosphor.json`, a map of icon name to SVG path data on a 256x256 grid, regenerated by
// `Scripts/gen_phosphor.py`. Icons are drawn as filled shapes, so they take the caller's foreground
// style and scale without rasterising.

/// The bundled Phosphor weights.
public enum PhosphorWeight: String, CaseIterable, Sendable {
    case light
    case fill

    var suffix: String { "-" + rawValue }
}

/// Loads `phosphor.json` once and caches each icon's parsed paths. Thread-safe.
enum PhosphorLibrary {

    /// Edge length of the grid every bundled icon is drawn on.
    static let viewBox: CGFloat = 256

    private static let lock = NSLock()
    private static var source: [String: [String]]?
    private static var parsed: [String: [Path]] = [:]
    private static var reportedMissing: Set<String> = []
    private static let log = Logger(subsystem: "noop.StrandDesign", category: "PhosphorIcon")

    /// The resource key for `name`. An explicit `-light` / `-fill` suffix wins over `weight`, and an
    /// Iconify `ph:` prefix is accepted so names can be pasted straight from a design frame.
    static func key(_ name: String, weight: PhosphorWeight) -> String {
        var trimmed = name.trimmingCharacters(in: .whitespaces)
        if trimmed.hasPrefix("ph:") { trimmed.removeFirst(3) }
        if PhosphorWeight.allCases.contains(where: { trimmed.hasSuffix($0.suffix) }) { return trimmed }
        return trimmed + weight.suffix
    }

    /// Every bundled icon key, sorted.
    static var allNames: [String] {
        lock.lock()
        defer { lock.unlock() }
        return loadedSource().keys.sorted()
    }

    static func exists(_ name: String, weight: PhosphorWeight) -> Bool {
        let key = key(name, weight: weight)
        lock.lock()
        defer { lock.unlock() }
        return loadedSource()[key] != nil
    }

    /// The icon's elements in viewBox coordinates, one `Path` per source element, or nil when the
    /// name is not bundled. Each element is filled on its own, matching how the SVG draws it.
    static func paths(_ name: String, weight: PhosphorWeight) -> [Path]? {
        let key = key(name, weight: weight)
        lock.lock()
        defer { lock.unlock() }
        if let cached = parsed[key] { return cached }
        guard let data = loadedSource()[key] else {
            if reportedMissing.insert(key).inserted {
                #if DEBUG
                log.error("Unknown Phosphor icon '\(key, privacy: .public)'; drawing an empty frame.")
                #endif
            }
            return nil
        }
        let paths = data.map(SVGPathParser.path)
        parsed[key] = paths
        return paths
    }

    /// Caller holds `lock`.
    private static func loadedSource() -> [String: [String]] {
        if let source { return source }
        let loaded = readResource()
        source = loaded
        return loaded
    }

    private static func readResource() -> [String: [String]] {
        guard let url = Bundle.module.url(forResource: "phosphor", withExtension: "json") else {
            log.error("phosphor.json is missing from the StrandDesign bundle.")
            return [:]
        }
        do {
            let data = try Data(contentsOf: url, options: .mappedIfSafe)
            return try JSONDecoder().decode([String: [String]].self, from: data)
        } catch {
            log.error("phosphor.json could not be read: \(error.localizedDescription, privacy: .public)")
            return [:]
        }
    }
}

/// A bundled Phosphor icon as a `Shape`, scaled uniformly from its 256x256 grid into the
/// largest centered square of the rect it is given.
///
/// All of the icon's elements are combined into one path filled with the non-zero rule. That is
/// identical to the source for every bundled icon except where two elements overlap with opposite
/// winding; `PhIcon` sidesteps that edge by filling each element separately.
public struct PhosphorShape: Shape {
    public let name: String
    public let weight: PhosphorWeight
    /// Index of a single source element to draw; nil draws every element.
    let element: Int?

    /// `name` may be given with or without its `-light` / `-fill` suffix; a suffix wins over `weight`.
    public init(_ name: String, weight: PhosphorWeight = .light) {
        self.init(name, weight: weight, element: nil)
    }

    init(_ name: String, weight: PhosphorWeight, element: Int?) {
        self.name = name
        self.weight = weight
        self.element = element
    }

    public func path(in rect: CGRect) -> Path {
        guard let elements = PhosphorLibrary.paths(name, weight: weight), !elements.isEmpty else {
            return Path()
        }
        let source: Path
        if let element {
            guard elements.indices.contains(element) else { return Path() }
            source = elements[element]
        } else if elements.count == 1 {
            source = elements[0]
        } else {
            var combined = Path()
            for part in elements { combined.addPath(part) }
            source = combined
        }
        let side = min(rect.width, rect.height)
        guard side > 0 else { return Path() }
        let scale = side / PhosphorLibrary.viewBox
        let transform = CGAffineTransform(a: scale, b: 0, c: 0, d: scale,
                                          tx: rect.midX - side / 2, ty: rect.midY - side / 2)
        return source.applying(transform)
    }
}

/// A Phosphor icon at a fixed square size, filled with the inherited foreground style.
///
///     PhIcon("heart")                      // heart-light, 18pt
///     PhIcon("play", weight: .fill, size: 24)
///     PhIcon("ph:sparkle-light").foregroundStyle(.secondary)
///
/// Unknown names draw nothing inside a frame of the same size, so layout never shifts; debug
/// builds log the name once. Icons are decorative by default (hidden from accessibility); give
/// the enclosing control its label.
public struct PhIcon: View {
    private let name: String
    private let weight: PhosphorWeight
    private let size: CGFloat

    public init(_ name: String, weight: PhosphorWeight = .light, size: CGFloat = 18) {
        self.name = name
        self.weight = weight
        self.size = size
    }

    /// True when `name` (with or without a weight suffix) is bundled in `weight`.
    public static func exists(_ name: String, weight: PhosphorWeight = .light) -> Bool {
        PhosphorLibrary.exists(name, weight: weight)
    }

    public var body: some View {
        let count = PhosphorLibrary.paths(name, weight: weight)?.count ?? 0
        ZStack {
            ForEach(0..<count, id: \.self) { element in
                PhosphorShape(name, weight: weight, element: element)
            }
        }
        .frame(width: size, height: size)
        .accessibilityHidden(true)
    }
}
