import Foundation
import XCTest
@testable import Strand

final class OpenRouterModelTests: XCTestCase {
    static let fixture = #"""
    {"data":[{"id":" z-ai/glm-5.3-flash ","name":" GLM 5.3 Flash ","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]},"pricing":{"prompt":"0.00000015","completion":"0.0000005"}},{"id":"vendor/free","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]},"pricing":{"prompt":"0","completion":"-0"}},{"id":"vendor/tiny","name":"Tiny","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]},"pricing":{"prompt":"0.00000000001","completion":"0.00000000004"}},{"id":"vendor/unknown","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]},"pricing":{"prompt":"NaN","completion":"-1"}},{"id":"vendor/invalid","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]},"pricing":{"prompt":"Infinity","completion":"1e308"}},{"id":"vendor/fraction","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]},"pricing":{"prompt":"0.0000000352","completion":"0.00000234567"}},{"id":"vendor/number","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]},"pricing":{"prompt":0,"completion":"0"}},{"id":"z-ai/glm-5.3-flash","name":"duplicate","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]}},{"id":"vendor/image","architecture":{"input_modalities":["text"],"output_modalities":["image"]}},{"id":"vendor/embedding","architecture":{"input_modalities":["text"],"output_modalities":["embeddings"]}},{"id":"vendor/audio","architecture":{"input_modalities":["audio"],"output_modalities":["text"]}},{"id":"z-ai/glm-5.3-flash:batch","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]}},{"id":" ","architecture":{"input_modalities":["text","image"],"output_modalities":["text"]}},{"id":"vendor/missing"},{"id":123,"architecture":{"input_modalities":["text","image"],"output_modalities":["text"]}}]}
    """#

    // Generated by swiftc -O OpenRouterModel.swift main.swift; copied verbatim into the Kotlin twin.
    private let expected = """
    z-ai/glm-5.3-flash|GLM 5.3 Flash|$0.15/$0.5
    vendor/free|vendor/free|$0/$0
    vendor/tiny|Tiny|<$0.0001/<$0.0001
    vendor/unknown|vendor/unknown|unknown
    vendor/invalid|vendor/invalid|unknown
    vendor/fraction|vendor/fraction|$0.0352/$2.3457
    vendor/number|vendor/number|unknown
    vendor/manual,z-ai/glm-5.3-flash,vendor/fraction,vendor/free,vendor/invalid,vendor/number,vendor/tiny,vendor/unknown
    """

    func testCatalogueAndPricesMatchCrossPlatformOracle() throws {
        let json = try JSONSerialization.jsonObject(with: Data(Self.fixture.utf8)) as! [String: Any]
        let models = OpenRouterModel.parse(json)
        var lines = models.map { m in
            let price = m.priceFigures.map { $0.input + "/" + $0.output } ?? "unknown"
            return m.id + "|" + m.displayName + "|" + price
        }
        lines.append(OpenRouterModel.orderedIDs(models, selected: "vendor/manual").joined(separator: ","))
        XCTAssertEqual(lines.joined(separator: "\n"), expected)
    }

    func testLiveListDropsUnavailableRecommendationsButPreservesSelection() {
        let live = [OpenRouterModel(id: "vendor/new"), OpenRouterModel(id: "minimax/minimax-m2.7")]
        XCTAssertEqual(OpenRouterModel.orderedIDs(live, selected: "retired/model"),
                       ["retired/model", "minimax/minimax-m2.7", "vendor/new"])
        XCTAssertEqual(OpenRouterModel.orderedIDs(live, selected: "vendor/new"),
                       ["minimax/minimax-m2.7", "vendor/new"])
    }

    func testProviderDefaultsAndModelParser() throws {
        XCTAssertEqual(AIProvider.openRouter.defaultModel, "z-ai/glm-5.3-flash")
        XCTAssertEqual(AIProvider.openRouter.modelOptions, OpenRouterModel.recommendedIDs)
        let json = try JSONSerialization.jsonObject(with: Data(Self.fixture.utf8)) as! [String: Any]
        XCTAssertEqual(OpenAIClient(provider: .openRouter).parseModels(json), OpenRouterModel.parse(json).map(\.id))
        XCTAssertTrue(OpenRouterModel.parse([:]).isEmpty)
    }
}
